#!/bin/sh
export DONE=0
while [ $DONE -eq 0 ]
do
DONE=1
netstat -pl | grep -e ":3001" -e ":3003" -e ":3004" -e ":3005" | sed -e 's/.*\s\([0-9]*\)\/\(.*\)/\1 \2/g' | sort -u| while read PID NAME
do
  DONE=0
  # kills the parent with signal 2 if possible. Otherwise the normal process
  if [ $PID -gt 0  ]
  then
     PPID=`ps -p $PID -o "ppid="`
     OWNER=`ps -p $PID -o "uid="`
     POWNER=`ps -p $PPID -o "uid="`
     if [ "$POWNER" -eq `id -u` ]
     then
        kill -2 $PPID
        echo killed SIGINT $NAME 1>&2
     else
       if [ $OWNER -eq `id -u` ]
       then
        kill $PID
        echo killed SIGTERM $NAME 1>&2
       fi
     fi
  fi
done
done
exit 0
