#!/bin/sh 
set -e
TMPDIR=`mktemp -d -t modbustcp`
export TMPDIR
trap 'echo signal 15 $TMPDIR; rm -rf $TMPDIR' 15
trap 'echo signal 2 $TMPDIR; rm -rf $TMPDIR' 2

rm -rf e2e/temp/yaml-dir e2e/temp/yaml-dir-addon 
mkdir -p $TMPDIR/yaml-dir/local
HTTPPORT=3004
if [ $# -ge 1 ]
then
    HTTPPORT=$1
fi
DEBUGTMPDIR=e2e/servers/modbus2mqtt.temp
if [ -r e2e/servers/modbus2mqtt.temp ]
then
    TMPDIR=$DEBUGTMPDIR
    rm -rf $TMPDIR/*
fi
mkdir -p $TMPDIR/local
echo modbus2mqtt $HTTPPORT $TMPDIR
echo 'httpport: '$HTTPPORT >$TMPDIR/local/modbus2mqtt.yaml
if [ $# -ge 2 ]
then
    echo "supervisor_host: localhost:3006" >>$TMPDIR/local/modbus2mqtt.yaml
    export HASSIO_TOKEN=abcd1234
fi
node dist/modbus2mqtt.js -y $TMPDIR -s $TMPDIR   