#!/bin/sh 
set -e
TMPDIR=`mktemp -d -t modbus2mqttXXXXX`
export TMPDIR
export MPID=$$
localhost="127.0.0.1"
trap 'echo signal 15 $MPID $TMPDIR; rm -rf $TMPDIR; kill -15 $MPID; exit 1' 15
trap 'echo signal 2 $MPID $TMPDIR; rm -rf $TMPDIR; kill -2 $MPID; exit 1;' 2

HTTPPORT=3004
if [ $# -ge 1 ]
then
    HTTPPORT=$1
fi
DEBUGTMPDIR=e2e/modbus2mqtt.temp
if [ -r e2e/modbus2mqtt.temp -a "$#" -ge 2 ]
then
    rm -rf $DEBUGTMPDIR/public
    rm -rf $DEBUGTMPDIR/modbus2mqtt/specifications
    rm -rf $DEBUGTMPDIR/modbus2mqtt/busses
    sleep infinity &
    MPID=$!
else
  mkdir -p $TMPDIR/modbus2mqtt
  echo 'httpport: '$HTTPPORT >$TMPDIR/modbus2mqtt/modbus2mqtt.yaml
  if [ $# -ge 2 ]
  then # port 3005
    echo "supervisor_host: $localhost:3006" >>$TMPDIR/modbus2mqtt/modbus2mqtt.yaml
    export HASSIO_TOKEN=abcd1234
  fi
  echo "TMPDIR=$TMPDIR"
  node dist/server/modbus2mqtt.js -c $TMPDIR  -d $TMPDIR -s $TMPDIR &
  MPID=$!  
fi
wait $MPID
