#!/bin/sh 
set -e
TMPDIR=`mktemp -d -t modbustcp`
export TMPDIR
trap 'echo signal 15 $TMPDIR; rm -rf $TMPDIR' 15
trap 'echo signal 2 $TMPDIR; rm -rf $TMPDIR' 2

echo homeassistant:homeassistant >$TMPDIR/password.txt 
mosquitto_passwd -U $TMPDIR/password.txt
chmod 600 $TMPDIR/password.txt
sed -e 's|<tmpdir>|'$TMPDIR'|g' <cypress/servers/mosquitto.conf >$TMPDIR/mosquitto.conf

if [ -r "/opt/homebrew/sbin/mosquitto" ] 
then
  EXEC=/opt/homebrew/sbin/mosquitto
fi
$EXEC -c $TMPDIR/mosquitto.conf
