#!/command/with-contenv sh
cd /var/lib/modbus2mqtt || { echo "ERROR: Cannot access home directory"; exit 1; }
export HOME=/var/lib/modbus2mqtt
s6-setuidgid modbus2mqtt /usr/bin/modbus2mqtt -c /config -d /data -s /ssl 2>&1
[ $? -ne 0 ] && echo "modbus2mqtt exited with error code $?" 2>&1
