ARG ALPINE_VERSION=3.22
FROM alpine:${ALPINE_VERSION}

# Install runtime and tooling to start service and perform healthchecks
 RUN apk add --no-cache s6-overlay nodejs npm curl

# Copy produced packages (expect build-and-test-image.sh to copy repo to ./packages)
COPY ./packages/ /tmp/packages/
# Find the produced apk and install it
RUN  ls /tmp/packages/*/modbus2mqtt-*.apk  | while read apk_file; do  apk add --allow-untrusted "$apk_file"; done

# Create service
RUN \
    s6dir=/etc/s6-overlay/s6-rc.d/modbus2mqtt && \
    mkdir -p $s6dir && \
    echo 'longrun' > $s6dir/type && \
    echo '#!/command/with-contenv sh' > $s6dir/run && \
    echo 'exec /usr/bin/modbus2mqtt 2>&1' >> $s6dir/run && \
    chmod +x $s6dir/run && \
    s6usr=/etc/s6-overlay/s6-rc.d/user/contents.d && \
    mkdir -p $s6usr && \
    touch $s6usr/modbus2mqtt && \
    mkdir -p $s6dir/dependencies.d && \
    touch $s6dir/dependencies.d/base && \  
    echo '#!/bin/sh' >$s6dir/finish && \
    echo 'echo modbus2mqtt done' >>$s6dir/finish && \
    chmod +x $s6dir/finish 

EXPOSE 3000

# Start service using s6-overlay
CMD ["/init"] 
